### ISSUE TITLE
undefined method `new' for Phoney:Module

### ISSUE THREAD

**Issue by hraynaud** [habermann24/phoney#14]
Not sure whats going on but I can't seem to create any Phoney instances?  This is very bizarre.

**Comment by habermann24** [comment]
The last gem release does not reflect the last master.

The name of the module used to be `PhoneNumber`. So try `PhoneNumber.new("...")` 
This project is more of a little experiment than a real library. I haven't had the time to really make it shine.

If you need good phone number formatting support, I would suggest https://github.com/sstephenson/global_phone

**Comment by hraynaud** [comment]
Thanks for the quick response.
